include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/l10n/**

linter:
  rules:
    prefer_single_quotes: true
    directives_ordering: true
    always_use_package_imports: true
    require_trailing_commas: true
